services:
  flask:
    image: flask
    build:
      context: flask
    env_file:
      - flask/.env
    volumes:
      - ./flask:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development


  angular:
    image: angular
    build: angular
    volumes:
      - ./angular/:/app


  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
      - "127.0.0.1:4200:4200"
    depends_on:
      - flask
    