services:
  flask:
    image: flask
    build:
      context: flask
    env_file:
      - flask/.env
    volumes:
      - ./flask:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development


  angular:
    image: angular
    build: angular
    ports:
      - "127.0.0.1:4200:4200"
    volumes:
      - ./angular/:/app


  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./angular/dist/rncp/browser:/usr/share/nginx/html
    depends_on:
      - flask
      - angular
    